config/routes.rb
Rails.application.routes.draw do
  root "droprates#index"
  resources :droprates
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/droprate.rb
class Droprate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/droprates_controller.rb
class DropratesController < ApplicationController
  before_action :set_droprate, only: %i[ show edit update destroy ]

  # GET /droprates or /droprates.json
  def index
    @droprates = Droprate.all
  end

  # GET /droprates/1 or /droprates/1.json
  def show
  end

  # GET /droprates/new
  def new
    @droprate = Droprate.new
  end

  # GET /droprates/1/edit
  def edit
  end

  # POST /droprates or /droprates.json
  def create
    @droprate = Droprate.new(droprate_params)

    respond_to do |format|
      if @droprate.save
        format.html { redirect_to droprate_url(@droprate), notice: "Droprate was successfully created." }
        format.json { render :show, status: :created, location: @droprate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @droprate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /droprates/1 or /droprates/1.json
  def update
      @droprate.update(droprate_params)
  end

  # DELETE /droprates/1 or /droprates/1.json
  def destroy
    @droprate.destroy!

    respond_to do |format|
      format.html { redirect_to droprates_url, notice: "Droprate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_droprate
      @droprate = Droprate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def droprate_params
      params.require(:droprate).permit(:item_name, :drop_chance, :boss_kills, :kills_per_drop)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/droprates_helper.rb
module DropratesHelper
end

app/views/droprates/_droprate.html.erb
<div id="<%= dom_id droprate %>">
  <%= render partial: "form", locals: { droprate: droprate} %>
</div>

app/views/droprates/_form.html.erb
<%= form_with(model: droprate, data: {
  controller: "drop-rate",
  drop_rate_id_value: droprate.id || 0
}) do |form| %>
  <div>
    <%= form.label :item_name, style: "display: block" %>
    <%= form.text_field :item_name %>
  </div>
  <div class="field">
    <%= form.label :kills_per_drop, "Kills per Drop" %>
    <%= form.number_field :kills_per_drop,
                          value: droprate.kills_per_drop || 0,
                          data: {
                            drop_rate_target: "killsPerDrop",
                            action: "input->drop-rate#convertToPercentage input->drop-rate#submitFormOnChange" } %>
  </div>
  <div class="field">
    <%= form.label :drop_chance %>
    <%= form.number_field :drop_chance, step: 0.0000001,
                          value: droprate.drop_chance || 0.0,
                          data: {
                            drop_rate_target: "dropChance",
                            action: "input->drop-rate#convertToKillsPerDrop input->drop-rate#submitFormOnChange" } %>
  </div>
  <div class="field">
    <%= form.label :boss_kills %>
    <%= form.number_field :boss_kills,
                          value: droprate.boss_kills || 0,
                          data: {
                            drop_rate_target: "bossKills",
                            action: "input->drop-rate#calculateReceivedProbability input->drop-rate#submitFormOnChange" } %>
  </div>
  <div class="field">
    <%= form.label :number_of_drops, "Number of Drops" %>
    <%= form.number_field :number_of_drops,
                          min: 0,
                          value: droprate.number_of_drops || 0,
                          data: {
                            drop_rate_target: "numberOfDrops",
                            action: "input->drop-rate#calculateReceivedProbability input->drop-rate#submitFormOnChange"
                          } %>
  </div>
  <div data-drop-rate-target="result"></div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/droprates/edit.html.erb
<h1>Editing droprate</h1>

<%= render "form", droprate: @droprate %>

<br>

<div>
  <%= link_to "Show this droprate", @droprate %> |
  <%= link_to "Back to droprates", droprates_path %>
</div>

app/views/droprates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Droprates</h1>

<div id="droprates">
  <% @droprates.each do |droprate| %>
    <%= render droprate %>
    <p>
      <%= link_to "Show this droprate", droprate %>
    </p>
  <% end %>
</div>

<%= link_to "New droprate", new_droprate_path %>

app/views/droprates/new.html.erb
<h1>New droprate</h1>

<%= render "form", droprate: @droprate %>

<br>

<div>
  <%= link_to "Back to droprates", droprates_path %>
</div>

app/views/droprates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @droprate %>

<div>
  <%= link_to "Edit this droprate", edit_droprate_path(@droprate) %> |
  <%= link_to "Back to droprates", droprates_path %>

  <%= button_to "Destroy this droprate", @droprate, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7DropRatesCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>